### ISSUE TITLE
Consider relaxing requirements in setup.py

### ISSUE THREAD

**Issue by msull** [fsndzomga/anonLLM#2]
Hello @fsndzomga --

Thanks for this utility, I was looking for something that did precisely this and think your implementation is nice. 

Currently your setup.py lists quite a large number of pins, primarily transitive dependencies that are not imported or used directly, including restrictions on the setuptools / pip version. 

https://github.com/fsndzomga/anonLLM/blob/master/setup.py#L26-L73

This can make it challenging to integrate into an application environment that has a number of pre-existing restrictions on dependencies. However I do not believe most of these pins are necessary for your project. The general guideline I follow and have seen repeated mantra-like for years is to try and be as widely accepting of deps as possible in your libraries, and specific for all deps in your applications.

I'd personally love to see the "install_requires" here cut down to a minimal version. For example here I believe the following would capture everything that is required, and allow much more flexibility for endusers wishing to use this project:

```
install_requires = [
    "pydantic>2",
    "openai",
    "Faker",
    "spacy",
]
```

I'd be happy to submit a PR for this if you are open to such a change.

Thanks!

Sully

**Comment by fsndzomga** [comment]
Thanks for the feedback Sully. I did a pip freeze of my env to determine the libraries to keep in the install_requires. Before submitting the PR, can you please walk me through the reasoning that led you to determine the minimal version of the install_requires ? I usually do "pipenv graph" to identify and get rid of transitive dependencies but I guess my method has limitations.

**Comment by msull** [comment]
In this case because the project size is so small I just took a quick look at the three individual python files to see what imports were being used. My goal would be to eliminate everything but those packages that are actually imported within the codebase, which is where the set of requirements in my suggestion came from. 

As for the particular versions (or lack thereof), those are mostly chosen based on a few assumptions/deductions.

1. that anyone installing this is also using a relatively recent version of spacy. A better pin is probably something like `spacy>3`, or if you knew an exact specific minimum version that was needed even better but most "spacy 3 installs " should work fine and it's unlikely the `3.7` release of spacy (which is available!) breaks your usage
2. `Faker` usage here is simple and the API there hasn't changed in ages, so likely this will work with whatever the user happens to have, if they have it pinned for some other reason
3. `pydantic` has had a recent 2.0 release with lots of deprecation and breaking changes in subsequent 2.x releases; I know the usage I added to load the model on the recent PR is 2.0+ only, thus the minimum here; it wouldn't require much effort to make this library compatible with both however, then eliminate the need for >2.
4. `openai` similarly the usage here is simple and likely to be compatible with a wide variety of openai versions

---

The `spacy` example above illustrates one pitfall of the pinning that's in place -- someone using spacy 3.7+ would be unable to use this library, though there is no reason it couldn't work for them.

The specific thing I ran into is related to the numpy pin; currently in your repo it is pinned like so:

https://github.com/fsndzomga/anonLLM/blob/b724045eb032aa9bfddc757908735ed22c967042/setup.py#L47

However a version of spacy that is compatible with your existing spacy pin allows a wider range of numpy versions:
https://github.com/explosion/spaCy/blob/6fc153a266f66944b72071d04fd112daa77ebac0/pyproject.toml#L9

I'm also using the clarafai-python package to do some LLM work, which has a hard pin of numpy:
https://github.com/Clarifai/clarifai-python/blob/643d3af64b71031f755b25089da5bdcf5c9251f2/requirements.txt#L3

Why do they have this hard-pin? I have no idea. This pin fits within the requirements for the spacy version I indicated, but because it falls out of the range pinned by your repo there is no way to reconcile all of these requirements within a single environment. 

Since your package isn't directly utilizing numpy though, there isn't any real reason you need to include it in your deps listing at all, you just need a compatible `spacy` with it's own requirements fulfilled.

**Comment by fsndzomga** [comment]
Alright. Thank you for the very clear explanations. I am happy to be learning from you too.
You can submit a PR for the change, I will approve it and deploy a new minor version of the package.
Franck
